"""empty message

Revision ID: 1109cc879c4f
Revises: 
Create Date: 2022-06-22 13:36:07.485583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1109cc879c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_name', sa.String(length=255), server_default='', nullable=True))
        batch_op.add_column(sa.Column('theme_path', sa.String(length=500), server_default='', nullable=True))
        batch_op.drop_column('theme_path_relative')
        batch_op.drop_column('theme_path_full')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_path_full', sa.VARCHAR(length=255), server_default=sa.text("'C:\\Users\\Sacic.DESKTOP-AOUUKTV\\Desktop\\raspberrypi\\src\\static/theme/'"), nullable=True))
        batch_op.add_column(sa.Column('theme_path_relative', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=True))
        batch_op.drop_column('theme_path')
        batch_op.drop_column('theme_name')

    # ### end Alembic commands ###
