"""empty message

Revision ID: 36b173e290ef
Revises: b2a7a08c6b7f
Create Date: 2022-06-19 11:50:49.933001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b173e290ef'
down_revision = 'b2a7a08c6b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Medias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Medias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('media_type', sa.INTEGER(), nullable=False),
    sa.Column('delay', sa.INTEGER(), nullable=False),
    sa.Column('google_slide', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
