"""empty message

Revision ID: 39cc5f7d6519
Revises: c835b6b07d5f
Create Date: 2022-06-19 13:41:22.966821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cc5f7d6519'
down_revision = 'c835b6b07d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_path_relative', sa.String(length=255), server_default='/', nullable=True))
        batch_op.add_column(sa.Column('theme_path_full', sa.String(length=255), server_default='/home/ismail424/nextsalah/raspberrypi/src/static/theme/', nullable=True))
        batch_op.drop_column('theme_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_path', sa.VARCHAR(length=255), server_default=sa.text("'/'"), nullable=True))
        batch_op.drop_column('theme_path_full')
        batch_op.drop_column('theme_path_relative')

    # ### end Alembic commands ###
