"""empty message

Revision ID: 512707175cc2
Revises: 4bf026f4743a
Create Date: 2022-05-05 23:18:06.728988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512707175cc2'
down_revision = '4bf026f4743a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), server_default='Test', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Languages', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
