"""empty message

Revision ID: 56cc5a969c51
Revises: 6481d9579786
Create Date: 2022-05-14 18:43:39.741267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '56cc5a969c51'
down_revision = '6481d9579786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Languages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Languages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monday', sa.VARCHAR(), nullable=False),
    sa.Column('tuesday', sa.VARCHAR(), nullable=False),
    sa.Column('wednesday', sa.VARCHAR(), nullable=False),
    sa.Column('thursday', sa.VARCHAR(), nullable=False),
    sa.Column('friday', sa.VARCHAR(), nullable=False),
    sa.Column('saturday', sa.VARCHAR(), nullable=False),
    sa.Column('sunday', sa.VARCHAR(), nullable=False),
    sa.Column('january', sa.VARCHAR(), nullable=False),
    sa.Column('february', sa.VARCHAR(), nullable=False),
    sa.Column('march', sa.VARCHAR(), nullable=False),
    sa.Column('april', sa.VARCHAR(), nullable=False),
    sa.Column('may', sa.VARCHAR(), nullable=False),
    sa.Column('june', sa.VARCHAR(), nullable=False),
    sa.Column('july', sa.VARCHAR(), nullable=False),
    sa.Column('august', sa.VARCHAR(), nullable=False),
    sa.Column('september', sa.VARCHAR(), nullable=False),
    sa.Column('october', sa.VARCHAR(), nullable=False),
    sa.Column('november', sa.VARCHAR(), nullable=False),
    sa.Column('december', sa.VARCHAR(), nullable=False),
    sa.Column('prayer', sa.VARCHAR(), nullable=False),
    sa.Column('begins', sa.VARCHAR(), nullable=False),
    sa.Column('iqamah', sa.VARCHAR(), nullable=False),
    sa.Column('next', sa.VARCHAR(), nullable=False),
    sa.Column('footer_text', sa.VARCHAR(), nullable=False),
    sa.Column('qr_code_text', sa.VARCHAR(), nullable=False),
    sa.Column('fajr', sa.VARCHAR(), nullable=False),
    sa.Column('sunrise', sa.VARCHAR(), nullable=False),
    sa.Column('dhuhr', sa.VARCHAR(), nullable=False),
    sa.Column('asr', sa.VARCHAR(), nullable=False),
    sa.Column('maghrib', sa.VARCHAR(), nullable=False),
    sa.Column('isha', sa.VARCHAR(), nullable=False),
    sa.Column('etc', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
