"""empty message

Revision ID: 610977ed8f92
Revises: 
Create Date: 2022-06-23 17:24:42.392574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610977ed8f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.drop_column('theme_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_name', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=True))

    # ### end Alembic commands ###
