"""empty message

Revision ID: 6481d9579786
Revises: 512707175cc2
Create Date: 2022-05-05 23:18:39.627298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6481d9579786'
down_revision = '512707175cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Languages', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), server_default=sa.text("'Test'"), nullable=False))

    # ### end Alembic commands ###
