"""empty message

Revision ID: 88bc14c3cfc7
Revises: 
Create Date: 2022-04-24 16:03:08.540258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bc14c3cfc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_src', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Integer(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('google_slide', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_format', sa.String(), nullable=False),
    sa.Column('timezone', sa.Float(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('prayer_offset_json', sa.String(), nullable=False),
    sa.Column('fixed_prayer_offset_json', sa.String(), nullable=False),
    sa.Column('translate_json', sa.String(), nullable=False),
    sa.Column('iqamah_bool', sa.Boolean(), nullable=False),
    sa.Column('qr_code_bool', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_src', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prayer_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('fajr', sa.String(), nullable=False),
    sa.Column('sunrise', sa.String(), nullable=False),
    sa.Column('dhuhr', sa.String(), nullable=False),
    sa.Column('asr', sa.String(), nullable=False),
    sa.Column('maghrib', sa.String(), nullable=False),
    sa.Column('isha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prayer_time')
    op.drop_table('Video')
    op.drop_table('Setting')
    op.drop_table('Media')
    op.drop_table('Image')
    # ### end Alembic commands ###
