"""empty message

Revision ID: a313ee108ec2
Revises: 56cc5a969c51
Create Date: 2022-05-26 12:18:34.151074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a313ee108ec2'
down_revision = '56cc5a969c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), server_default='en', nullable=False))
        batch_op.drop_column('march')
        batch_op.drop_column('december')
        batch_op.drop_column('friday')
        batch_op.drop_column('monday')
        batch_op.drop_column('june')
        batch_op.drop_column('may')
        batch_op.drop_column('wednesday')
        batch_op.drop_column('july')
        batch_op.drop_column('november')
        batch_op.drop_column('tuesday')
        batch_op.drop_column('august')
        batch_op.drop_column('february')
        batch_op.drop_column('sunday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('january')
        batch_op.drop_column('april')
        batch_op.drop_column('october')
        batch_op.drop_column('saturday')
        batch_op.drop_column('september')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('september', sa.VARCHAR(), server_default=sa.text("'September'"), nullable=False))
        batch_op.add_column(sa.Column('saturday', sa.VARCHAR(), server_default=sa.text("'Saturday'"), nullable=False))
        batch_op.add_column(sa.Column('october', sa.VARCHAR(), server_default=sa.text("'October'"), nullable=False))
        batch_op.add_column(sa.Column('april', sa.VARCHAR(), server_default=sa.text("'April'"), nullable=False))
        batch_op.add_column(sa.Column('january', sa.VARCHAR(), server_default=sa.text("'January'"), nullable=False))
        batch_op.add_column(sa.Column('thursday', sa.VARCHAR(), server_default=sa.text("'Thursday'"), nullable=False))
        batch_op.add_column(sa.Column('sunday', sa.VARCHAR(), server_default=sa.text("'Sunday'"), nullable=False))
        batch_op.add_column(sa.Column('february', sa.VARCHAR(), server_default=sa.text("'February'"), nullable=False))
        batch_op.add_column(sa.Column('august', sa.VARCHAR(), server_default=sa.text("'August'"), nullable=False))
        batch_op.add_column(sa.Column('tuesday', sa.VARCHAR(), server_default=sa.text("'Tuesday'"), nullable=False))
        batch_op.add_column(sa.Column('november', sa.VARCHAR(), server_default=sa.text("'November'"), nullable=False))
        batch_op.add_column(sa.Column('july', sa.VARCHAR(), server_default=sa.text("'July'"), nullable=False))
        batch_op.add_column(sa.Column('wednesday', sa.VARCHAR(), server_default=sa.text("'Wednesday'"), nullable=False))
        batch_op.add_column(sa.Column('may', sa.VARCHAR(), server_default=sa.text("'May'"), nullable=False))
        batch_op.add_column(sa.Column('june', sa.VARCHAR(), server_default=sa.text("'June'"), nullable=False))
        batch_op.add_column(sa.Column('monday', sa.VARCHAR(), server_default=sa.text("'Monday'"), nullable=False))
        batch_op.add_column(sa.Column('friday', sa.VARCHAR(), server_default=sa.text("'Friday'"), nullable=False))
        batch_op.add_column(sa.Column('december', sa.VARCHAR(), server_default=sa.text("'December'"), nullable=False))
        batch_op.add_column(sa.Column('march', sa.VARCHAR(), server_default=sa.text("'March'"), nullable=False))
        batch_op.drop_column('language')

    # ### end Alembic commands ###
